import type { AtakPreferenceType } from "./atak-preferences.js";

/*
 * Generated from ATAK_PREFERENCES.md in the private planning repository: ATAK-CIV `main` at
 * 9f6893dd657f (ATAK 5.5.1.10), every preference XML in `atak/ATAK/app/src/main/res/xml/`. Keys,
 * types, defaults and value codes are ATAK's; descriptions and value labels are our own wording,
 * because ATAK's titles come from its GPL `strings.xml`.
 */

export type AtakPreferenceUse = "form" | "member" | "warning" | "advanced";

export interface AtakCatalogValue {
  value: string;
  label: string;
}

export interface AtakCatalogKey {
  key: string;
  /** Subgroup within the topic, such as "Altitude"; keys of a group are listed together. */
  group: string;
  /** The class ATAK stores; lists and text fields are strings, also for numbers. */
  type: AtakPreferenceType;
  /** ATAK's own default, used by "Reset to ATAK default"; `null` when ATAK sets none. */
  defaultValue: string | null;
  /** Allowed values of a list; `null` for free values. */
  values: AtakCatalogValue[] | null;
  /** Text fields that ATAK reads as numbers. */
  numeric: boolean;
  description: string;
  /** `form`: a ready field; `member`: only for single members; `warning`: allowed with a warning; `advanced`: hidden by default. */
  use: AtakPreferenceUse | null;
}

export interface AtakCatalogTopic {
  id: string;
  title: string;
  description: string;
  keys: AtakCatalogKey[];
}

export const ATAK_PREFERENCE_TOPICS: AtakCatalogTopic[] = [
  {
    id: "display-and-units",
    title: "Display and units",
    description: "Unit display, grid and coordinate readouts.",
    keys: [
      { key: "coord_display_pref", group: "Coordinates", type: "string", defaultValue: "MGRS", values: [{ value: "MGRS", label: "MGRS" }, { value: "DD", label: "Decimal degrees" }, { value: "DM", label: "Degrees, minutes" }, { value: "DMS", label: "Degrees, minutes, seconds" }, { value: "UTM", label: "UTM" }], numeric: false, description: "Coordinate format everywhere in the app", use: "form" },
      { key: "alt_display_pref", group: "Altitude", type: "string", defaultValue: "MSL", values: [{ value: "HAE", label: "Height above ellipsoid (HAE)" }, { value: "MSL", label: "Mean sea level (MSL)" }], numeric: false, description: "Altitude reference", use: "form" },
      { key: "alt_unit_pref", group: "Altitude", type: "string", defaultValue: "0", values: [{ value: "0", label: "Feet" }, { value: "1", label: "Meters" }], numeric: false, description: "Altitude unit (0 feet, 1 meters)", use: "form" },
      { key: "alt_display_agl", group: "Altitude", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Also show height above ground", use: "form" },
      { key: "speed_unit_pref", group: "Units", type: "string", defaultValue: "0", values: [{ value: "0", label: "mph" }, { value: "1", label: "km/h" }, { value: "2", label: "Knots" }, { value: "3", label: "m/s" }], numeric: false, description: "Speed unit (0 mph, 1 km/h, 2 knots, 3 m/s)", use: "form" },
      { key: "rab_rng_units_pref", group: "Units", type: "string", defaultValue: "1", values: [{ value: "0", label: "Feet, miles" }, { value: "1", label: "Meters, kilometers" }, { value: "2", label: "Nautical miles" }], numeric: false, description: "Distance unit (0 imperial, 1 metric, 2 nautical)", use: "form" },
      { key: "rab_brg_units_pref", group: "Direction", type: "string", defaultValue: "0", values: [{ value: "0", label: "Degrees" }, { value: "1", label: "Mils" }], numeric: false, description: "Bearing unit (0 degrees, 1 mils)", use: "form" },
      { key: "rab_north_ref_pref", group: "Direction", type: "string", defaultValue: "1", values: [{ value: "0", label: "True north" }, { value: "1", label: "Magnetic north" }, { value: "2", label: "Grid north" }], numeric: false, description: "North reference (0 true, 1 magnetic, 2 grid)", use: "form" },
      { key: "compass_heading_display", group: "Direction", type: "string", defaultValue: "Numeric", values: [{ value: "Numeric", label: "Number" }, { value: "Cardinal", label: "Cardinal direction" }], numeric: false, description: "Heading as number or cardinal direction", use: "form" },
      { key: "rab_dist_slant_range", group: "Range and bearing lines", type: "string", defaultValue: "clamped", values: [{ value: "slantrange", label: "Slant range" }, { value: "clamped", label: "Along the ground" }], numeric: false, description: "Range line distance: slant or ground-clamped", use: null },
      { key: "rng_feet_display_pref", group: "Units", type: "string", defaultValue: "5280", values: null, numeric: true, description: "Switch from feet to miles above this value", use: null },
      { key: "rng_meters_display_pref", group: "Units", type: "string", defaultValue: "2000", values: null, numeric: true, description: "Switch from meters to kilometers above this value", use: null },
      { key: "rab_color_pref", group: "Range and bearing lines", type: "string", defaultValue: "red", values: [{ value: "red", label: "red" }, { value: "yellow", label: "yellow" }, { value: "green", label: "green" }, { value: "cyan", label: "cyan" }, { value: "blue", label: "blue" }, { value: "magenta", label: "magenta" }, { value: "white", label: "white" }, { value: "black", label: "black" }], numeric: false, description: "Default colour of range and bearing lines", use: null },
      { key: "rab_preference_show_eta", group: "Range and bearing lines", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Show ETA on range and bearing labels", use: null },
      { key: "set_domain_pref", group: "Units", type: "string", defaultValue: "Ground", values: [{ value: "Ground", label: "Ground" }, { value: "Aviation", label: "Aviation" }, { value: "Maritime", label: "Maritime" }], numeric: false, description: "Label set for ground, aviation or maritime use", use: "form" },
      { key: "pref_grid_type", group: "Grid and layer outlines", type: "string", defaultValue: "MGRS", values: [{ value: "MGRS", label: "MGRS" }, { value: "Decimal Degrees", label: "Decimal Degrees" }, { value: "Degrees, Minutes, Seconds", label: "Degrees, Minutes, Seconds" }], numeric: false, description: "Grid line type", use: null },
      { key: "pref_grid_color", group: "Grid and layer outlines", type: "string", defaultValue: "#ffffff", values: [{ value: "#ffffff", label: "White" }, { value: "#ff00ff", label: "Magenta" }, { value: "#00ff00", label: "Green" }, { value: "#ffff00", label: "Yellow" }, { value: "Custom", label: "Custom" }], numeric: false, description: "Grid line colour", use: null },
      { key: "prefs_grid_default_show", group: "Grid and layer outlines", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Show grid lines on start", use: null },
      { key: "pref_layer_outline_color", group: "Grid and layer outlines", type: "string", defaultValue: "#00ff00", values: [{ value: "#ffffff", label: "White" }, { value: "#ff00ff", label: "Magenta" }, { value: "#00ff00", label: "Green" }, { value: "#ffff00", label: "Yellow" }], numeric: false, description: "Layer outline colour", use: null },
      { key: "prefs_layer_outlines_default_show", group: "Grid and layer outlines", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Show layer outlines on start", use: null },
      { key: "self_coord_info_display", group: "Coordinates", type: "string", defaultValue: "bottom_right", values: [{ value: "bottom_right", label: "Box at the bottom right" }, { value: "bottom_bar", label: "Bar at the bottom" }, { value: "none", label: "Hidden" }], numeric: false, description: "Where the own coordinate box is shown", use: null },
      { key: "self_coord_action", group: "Coordinates", type: "string", defaultValue: "panto", values: [{ value: "nothing", label: "Nothing" }, { value: "cyclecoordinate", label: "Cycle the coordinate format" }, { value: "panto", label: "Pan to own position" }], numeric: false, description: "What tapping the own coordinate box does", use: null },
      { key: "selfcoord_legacy_enlarge", group: "Coordinates", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Allow enlarging the coordinate box", use: null },
    ],
  },
  {
    id: "map-and-screen",
    title: "Map and screen",
    description: "Map controls, labels and rendering.",
    keys: [
      { key: "map_zoom_visible", group: "Map controls", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Show zoom buttons", use: null },
      { key: "map_eyealt_visible", group: "Map controls", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Show eye-altitude zoom control", use: null },
      { key: "map_scale_visible", group: "Map controls", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Show map scale", use: null },
      { key: "map_scale_rounding", group: "Map controls", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Round the map scale", use: null },
      { key: "map_center_designator", group: "Map controls", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Mark the map centre", use: null },
      { key: "atakControlShowLabels", group: "Markers and labels", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Show marker labels", use: "form" },
      { key: "atakControlShortenLabels", group: "Markers and labels", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Shorten long marker labels", use: null },
      { key: "displayAsSymbologyGraphic", group: "Markers and labels", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Show other users as military symbols", use: null },
      { key: "location_marker_scale_key", group: "Markers and labels", type: "string", defaultValue: "-1", values: [{ value: "-1", label: "Standard" }, { value: "40", label: "1×" }, { value: "48", label: "2×" }, { value: "56", label: "3×" }, { value: "64", label: "4×" }], numeric: false, description: "Size of the own position marker", use: null },
      { key: "atakGlobeModeEnabled", group: "Rendering", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Allow globe display", use: null },
      { key: "frame_limit", group: "Rendering", type: "string", defaultValue: "0", values: [{ value: "0", label: "Full speed" }, { value: "1", label: "Battery saver" }], numeric: false, description: "Render speed (0 full, 1 battery saver)", use: null },
      { key: "atakContinuousRender", group: "Rendering", type: "boolean", defaultValue: null, values: null, numeric: false, description: "Render continuously", use: "advanced" },
      { key: "imagery_tab_name", group: "Panels and overlays", type: "string", defaultValue: "Imagery", values: [{ value: "Imagery", label: "Imagery" }, { value: "Maps", label: "Maps" }], numeric: false, description: "Name of the imagery tab", use: null },
      { key: "overlay_manager_width_height", group: "Panels and overlays", type: "string", defaultValue: "33", values: [{ value: "50", label: "50 %" }, { value: "33", label: "33 %" }, { value: "25", label: "25 %" }], numeric: false, description: "Overlay manager panel size (percent)", use: null },
      { key: "sidepane_handle_shade", group: "Panels and overlays", type: "string", defaultValue: "Dark", values: [{ value: "Light", label: "Light" }, { value: "Dark", label: "Dark" }], numeric: false, description: "Side pane handle shade", use: null },
      { key: "scrollToSelfOnStart", group: "Map controls", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Centre on own position at start", use: null },
      { key: "disableFloatToBottom", group: "Map controls", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Keep own position centred while moving", use: null },
      { key: "volumemapswitcher", group: "Map controls", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Volume keys switch map layers", use: null },
      { key: "prefs_layer_grg_map_interaction", group: "Panels and overlays", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Allow interaction with image overlays", use: null },
      { key: "grgRootVisibilityToggle", group: "Panels and overlays", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Mass visibility toggle for image overlays", use: null },
      { key: "dpgkRootVisibilityToggle", group: "Panels and overlays", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Mass visibility toggle for Data Package overlays", use: null },
      { key: "prefs_file_label", group: "Markers and labels", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Show labels of imported shapes", use: null },
    ],
  },
  {
    id: "operation",
    title: "Operation",
    description: "Touch, buttons, text size and device behaviour.",
    keys: [
      { key: "largeTextMode", group: "Size and text", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Large text", use: "form" },
      { key: "largeActionBar", group: "Size and text", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Large toolbar", use: null },
      { key: "relativeOverlaysScalingRadioList", group: "Size and text", type: "string", defaultValue: "1", values: [{ value: "1", label: "Normal" }, { value: "1.25", label: "1.25×" }, { value: "1.5", label: "1.5×" }, { value: "1.75", label: "1.75×" }, { value: "2", label: "2×" }], numeric: false, description: "Icon and text scale", use: null },
      { key: "label_text_size", group: "Size and text", type: "string", defaultValue: "14", values: [{ value: "14", label: "Normal" }, { value: "16", label: "Large" }, { value: "18", label: "Extra large" }], numeric: false, description: "Default label size", use: null },
      { key: "nav_orientation_right", group: "Toolbar", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Toolbar on the right side", use: null },
      { key: "landscape_extended_buttons", group: "Toolbar", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "More toolbar icons in landscape", use: null },
      { key: "atakLongPressMap", group: "Touch and buttons", type: "string", defaultValue: "actionbar", values: [{ value: "nothing", label: "Nothing" }, { value: "actionbar", label: "Show or hide the toolbar" }, { value: "dropicon", label: "Drop a marker" }, { value: "redx", label: "Drop a red X" }], numeric: false, description: "Action on long press on the map", use: null },
      { key: "atakDoubleTapToZoom", group: "Touch and buttons", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Double tap zooms in", use: null },
      { key: "atakControlQuitOnBack", group: "Touch and buttons", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Back button quits the app", use: null },
      { key: "atakControlAskToQuit", group: "Touch and buttons", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Ask before quitting", use: null },
      { key: "atakBackButtonCenterSelf", group: "Touch and buttons", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Back button no longer centres on self", use: null },
      { key: "tilt_rotation_menu_auto_close", group: "Touch and buttons", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Close the tilt and rotation menu automatically", use: null },
      { key: "disable_autolink_mapitem_links", group: "Touch and buttons", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Do not open linked items automatically", use: null },
      { key: "broadcast_disable", group: "Toolbar", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Hide the broadcast button", use: null },
      { key: "dexControls", group: "Screen and device", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Controls for Samsung DeX", use: null },
      { key: "faux_nav_bar", group: "Screen and device", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "On-screen navigation bar", use: null },
      { key: "faux_nav_bar_reverse", group: "Screen and device", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Reverse the on-screen navigation bar", use: null },
      { key: "atakAdjustCurvedDisplay", group: "Screen and device", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Adjust for curved displays", use: null },
      { key: "atakScreenLock", group: "Screen and device", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Keep the screen on", use: "form" },
      { key: "atakForcedBrightness", group: "Screen and device", type: "string", defaultValue: "-1", values: [{ value: "-1", label: "Device setting" }, { value: "0", label: "Lowest" }, { value: "25", label: "25 %" }, { value: "50", label: "50 %" }, { value: "75", label: "75 %" }, { value: "100", label: "100 %" }], numeric: false, description: "Fixed app brightness (-1 none)", use: null },
      { key: "dim_map_with_brightness_key", group: "Screen and device", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Dim map overlays with brightness", use: null },
      { key: "atakControlReverseOrientation", group: "Screen and device", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Reverse landscape orientation", use: null },
      { key: "atakDisableSoftkeyIllumination", group: "Screen and device", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Turn off soft key lighting", use: null },
      { key: "atakForceAirplaneRadioList", group: "Screen and device", type: "string", defaultValue: "none", values: [{ value: "none", label: "Do not force" }, { value: "cell", label: "Cellular off" }, { value: "cell,wifi", label: "Cellular and Wi-Fi off" }], numeric: false, description: "Force radios off (none, cell, cell and Wi-Fi)", use: "warning" },
      { key: "disableLeyGuard", group: "Screen and device", type: "boolean", defaultValue: null, values: null, numeric: false, description: "Disable the keyguard (key spelled as in ATAK)", use: "warning" },
      { key: "forceEnglish", group: "Screen and device", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Ignore the device language", use: null },
      { key: "night_vision_widget", group: "Night vision", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Night vision control inside ATAK", use: null },
      { key: "loc_map_widget", group: "Night vision", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Night vision from the map widget", use: null },
      { key: "loc_notification", group: "Night vision", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Night vision from the notification panel", use: null },
      { key: "loc_self_overlay_box", group: "Night vision", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Night vision from the own location box", use: null },
      { key: "centerDesignatorDuringPointDrop", group: "Dropping points", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Centre designator while dropping points", use: null },
      { key: "legacyPointDropNaming", group: "Dropping points", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Old naming of dropped points", use: null },
    ],
  },
  {
    id: "position-reporting",
    title: "Position reporting",
    description: "How often and what the app reports about itself.",
    keys: [
      { key: "locationReportingStrategy", group: "Reporting", type: "string", defaultValue: "Dynamic", values: [{ value: "Dynamic", label: "Dynamic (more often when moving)" }, { value: "Constant", label: "Constant interval" }], numeric: false, description: "Dynamic or constant reporting", use: "form" },
      { key: "dynamicReportingRateStationaryReliable", group: "Rates over the server", type: "string", defaultValue: "180", values: null, numeric: true, description: "Dynamic, stationary, server (seconds)", use: "form" },
      { key: "dynamicReportingRateMinReliable", group: "Rates over the server", type: "string", defaultValue: "20", values: null, numeric: true, description: "Dynamic, slowest moving rate, server (seconds)", use: "form" },
      { key: "dynamicReportingRateMaxReliable", group: "Rates over the server", type: "string", defaultValue: "2", values: null, numeric: true, description: "Dynamic, fastest rate, server (seconds)", use: "form" },
      { key: "constantReportingRateReliable", group: "Rates over the server", type: "string", defaultValue: "15", values: null, numeric: true, description: "Constant rate, server (seconds)", use: "form" },
      { key: "dynamicReportingRateStationaryUnreliable", group: "Rates over the mesh", type: "string", defaultValue: "30", values: null, numeric: true, description: "Dynamic, stationary, mesh (seconds)", use: "form" },
      { key: "dynamicReportingRateMinUnreliable", group: "Rates over the mesh", type: "string", defaultValue: "20", values: null, numeric: true, description: "Dynamic, slowest moving rate, mesh (seconds)", use: "form" },
      { key: "dynamicReportingRateMaxUnreliable", group: "Rates over the mesh", type: "string", defaultValue: "2", values: null, numeric: true, description: "Dynamic, fastest rate, mesh (seconds)", use: "form" },
      { key: "constantReportingRateUnreliable", group: "Rates over the mesh", type: "string", defaultValue: "3", values: null, numeric: true, description: "Constant rate, mesh (seconds)", use: "form" },
      { key: "dispatchLocationCotExternal", group: "Reporting", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Send own contact information", use: null },
      { key: "dispatchLocationCotExternalAtStart", group: "Reporting", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Report before the first GPS fix", use: null },
      { key: "dispatchLocationHidden", group: "Reporting", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Hide own position", use: "warning" },
      { key: "dispatchTAKVersionNumber", group: "Reporting", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Report the app version (Core names packages from it)", use: "warning" },
      { key: "restoreRecordedLocation", group: "Reporting", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Restore last position on restart", use: null },
      { key: "mockingOption", group: "GPS", type: "string", defaultValue: "WRGPS", values: [{ value: "IgnoreInternalGPS", label: "External GPS only" }, { value: "LocalGPS", label: "Internal GPS only" }, { value: "WRGPS", label: "External, then internal" }], numeric: false, description: "GPS source (internal, external, both)", use: null },
      { key: "listenPort", group: "GPS", type: "string", defaultValue: "4349", values: null, numeric: true, description: "Port for network GPS", use: null },
      { key: "useGPSTime", group: "GPS", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Use GPS time", use: null },
      { key: "useTerrainElevationSelfMarker", group: "GPS", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Own elevation from terrain data instead of GPS", use: null },
    ],
  },
  {
    id: "stale-data-and-tracks",
    title: "Stale data and tracks",
    description: "When old items disappear and how tracks are kept.",
    keys: [
      { key: "expireStaleItemsTime", group: "Stale items", type: "string", defaultValue: "5", values: [{ value: "0", label: "Immediately" }, { value: "1", label: "1 minute" }, { value: "5", label: "5 minutes" }, { value: "20", label: "20 minutes" }, { value: "60", label: "1 hour" }, { value: "360", label: "6 hours" }, { value: "1440", label: "1 day" }], numeric: false, description: "Remove stale items after (minutes)", use: "form" },
      { key: "expireEverything", group: "Stale items", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Remove every marker type when stale", use: null },
      { key: "expireUnknowns", group: "Stale items", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Remove unknown markers when stale", use: null },
      { key: "staleRemoteDisconnects", group: "Stale items", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Stale users when they disconnect from the server", use: null },
      { key: "toggle_offscreen_indicators", group: "Off-screen indicators", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Indicators for off-screen users", use: null },
      { key: "offscreen_indicator_dist_threshold", group: "Off-screen indicators", type: "string", defaultValue: "10", values: null, numeric: true, description: "Off-screen indicator distance (km)", use: null },
      { key: "offscreen_indicator_timeout_threshold", group: "Off-screen indicators", type: "string", defaultValue: "60", values: null, numeric: true, description: "Off-screen indicator timeout (seconds, 0 off)", use: null },
      { key: "toggle_log_tracks", group: "Own track", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Record own track", use: null },
      { key: "track_infinite", group: "Own track", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Keep own track across restarts", use: null },
      { key: "track_prefix", group: "Own track", type: "string", defaultValue: "track_", values: null, numeric: false, description: "Track name prefix", use: null },
      { key: "toggle_rotate_track_colors", group: "Own track", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Rotate track colours", use: null },
      { key: "max_num_bread_tracks", group: "Breadcrumbs", type: "integer", defaultValue: "200", values: null, numeric: false, description: "Maximum breadcrumbs", use: null },
      { key: "bread_dist_threshold", group: "Breadcrumbs", type: "string", defaultValue: "2", values: null, numeric: true, description: "Breadcrumb distance (meters)", use: null },
      { key: "bread_track_timegap_threshold", group: "Own track", type: "string", defaultValue: "10", values: null, numeric: true, description: "Gap that splits server tracks (minutes)", use: null },
      { key: "track_crumb_size", group: "Breadcrumbs", type: "string", defaultValue: "10", values: [{ value: "10", label: "Normal" }, { value: "15", label: "Large" }, { value: "20", label: "Extra large" }], numeric: false, description: "Breadcrumb size", use: null },
      { key: "track_line_to_surface", group: "Breadcrumbs", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Draw tracks down to the ground in 3D", use: null },
      { key: "track_csv_export_headers", group: "Track export", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "CSV export with header", use: null },
      { key: "track_kml_export_timestamps", group: "Track export", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "KML export with timestamps", use: null },
    ],
  },
  {
    id: "routes-and-navigation",
    title: "Routes and navigation",
    description: "Checkpoints, arrival radii and Bloodhound.",
    keys: [
      { key: "waypointPrefix", group: "Navigation", type: "string", defaultValue: "CP", values: null, numeric: false, description: "Checkpoint name prefix", use: null },
      { key: "route_track_up_locked_on", group: "Navigation", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Track-up while navigating", use: null },
      { key: "useRouteVoiceCues", group: "Navigation", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Voice cues", use: null },
      { key: "route_vibrate_at_checkpoint", group: "Navigation", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Vibrate at checkpoints", use: null },
      { key: "waypointBubble.Walking", group: "Arrival radii", type: "string", defaultValue: "10", values: null, numeric: true, description: "Checkpoint radius walking (m)", use: null },
      { key: "waypointOffRouteBubble.Walking", group: "Arrival radii", type: "string", defaultValue: "10", values: null, numeric: true, description: "Off-route radius walking (m)", use: null },
      { key: "waypointBubble.Driving", group: "Arrival radii", type: "string", defaultValue: "20", values: null, numeric: true, description: "Checkpoint radius driving (m)", use: null },
      { key: "waypointOffRouteBubble.Driving", group: "Arrival radii", type: "string", defaultValue: "20", values: null, numeric: true, description: "Off-route radius driving (m)", use: null },
      { key: "waypointBubble.Flying", group: "Arrival radii", type: "string", defaultValue: "1000", values: null, numeric: true, description: "Checkpoint radius flying (m)", use: null },
      { key: "waypointOffRouteBubble.Flying", group: "Arrival radii", type: "string", defaultValue: "1000", values: null, numeric: true, description: "Off-route radius flying (m)", use: null },
      { key: "waypointBubble.Swimming", group: "Arrival radii", type: "string", defaultValue: "10", values: null, numeric: true, description: "Checkpoint radius swimming (m)", use: null },
      { key: "waypointOffRouteBubble.Swimming", group: "Arrival radii", type: "string", defaultValue: "10", values: null, numeric: true, description: "Off-route radius swimming (m)", use: null },
      { key: "waypointBubble.Watercraft", group: "Arrival radii", type: "string", defaultValue: "100", values: null, numeric: true, description: "Checkpoint radius watercraft (m)", use: null },
      { key: "waypointOffRouteBubble.Watercraft", group: "Arrival radii", type: "string", defaultValue: "100", values: null, numeric: true, description: "Off-route radius watercraft (m)", use: null },
      { key: "route_billboard_enabled", group: "Navigation", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Show attachment billboards", use: null },
      { key: "route_billboard_distance_m", group: "Navigation", type: "string", defaultValue: "500", values: null, numeric: true, description: "Billboard distance (m)", use: null },
      { key: "elevProfileInterpolateAlt", group: "Elevation profile", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Interpolate elevation profile", use: null },
      { key: "elevProfileCenterOnSeeker", group: "Elevation profile", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Centre elevation profile on seeker", use: null },
      { key: "gpxImportCheckpointsForNamedRoutePoints", group: "Route import and export", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "GPX import: named points become checkpoints", use: null },
      { key: "kmlExportGroundClamp", group: "Route import and export", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "KML export without elevation", use: null },
      { key: "kmlExportCheckpointMode", group: "Route import and export", type: "string", defaultValue: "Both", values: [{ value: "Points", label: "Points" }, { value: "Line", label: "Line" }, { value: "Both", label: "Points and line" }], numeric: false, description: "KML export of routes as points, line or both", use: null },
      { key: "rab_bloodhound_display_textwidget", group: "Bloodhound", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Bloodhound text widget", use: null },
      { key: "rab_bloodhound_large_textwidget", group: "Bloodhound", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Large Bloodhound text widget", use: null },
      { key: "rab_bloodhound_flash_colors", group: "Bloodhound", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Bloodhound flashes when closing in", use: null },
      { key: "rab_bloodhound_zoom", group: "Bloodhound", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Bloodhound auto zoom", use: null },
      { key: "bloodhound_flash_eta", group: "Bloodhound ETA", type: "string", defaultValue: "360", values: null, numeric: true, description: "Flash below ETA (seconds)", use: null },
      { key: "bloodhound_outer_eta", group: "Bloodhound ETA", type: "string", defaultValue: "180", values: null, numeric: true, description: "Outer to middle ETA (seconds)", use: null },
      { key: "bloodhound_inner_eta", group: "Bloodhound ETA", type: "string", defaultValue: "60", values: null, numeric: true, description: "Middle to inner ETA (seconds)", use: null },
      { key: "bloodhound_flash_color_pref", group: "Bloodhound ETA", type: "string", defaultValue: "black", values: [{ value: "red", label: "red" }, { value: "yellow", label: "yellow" }, { value: "green", label: "green" }, { value: "cyan", label: "cyan" }, { value: "blue", label: "blue" }, { value: "magenta", label: "magenta" }, { value: "white", label: "white" }, { value: "black", label: "black" }], numeric: false, description: "Flash colour", use: null },
      { key: "bloodhound_outer_color_pref", group: "Bloodhound ETA", type: "string", defaultValue: "green", values: [{ value: "red", label: "red" }, { value: "yellow", label: "yellow" }, { value: "green", label: "green" }, { value: "cyan", label: "cyan" }, { value: "blue", label: "blue" }, { value: "magenta", label: "magenta" }, { value: "white", label: "white" }, { value: "black", label: "black" }], numeric: false, description: "Outer colour", use: null },
      { key: "bloodhound_middle_color_pref", group: "Bloodhound ETA", type: "string", defaultValue: "yellow", values: [{ value: "red", label: "red" }, { value: "yellow", label: "yellow" }, { value: "green", label: "green" }, { value: "cyan", label: "cyan" }, { value: "blue", label: "blue" }, { value: "magenta", label: "magenta" }, { value: "white", label: "white" }, { value: "black", label: "black" }], numeric: false, description: "Middle colour", use: null },
      { key: "bloodhound_inner_color_pref", group: "Bloodhound ETA", type: "string", defaultValue: "red", values: [{ value: "red", label: "red" }, { value: "yellow", label: "yellow" }, { value: "green", label: "green" }, { value: "cyan", label: "cyan" }, { value: "blue", label: "blue" }, { value: "magenta", label: "magenta" }, { value: "white", label: "white" }, { value: "black", label: "black" }], numeric: false, description: "Inner colour", use: null },
      { key: "bloodhound_reroute_distance_pref", group: "Bloodhound", type: "string", defaultValue: "20.0", values: null, numeric: true, description: "Reroute distance", use: null },
      { key: "bloodhound_reroute_timer_pref", group: "Bloodhound", type: "string", defaultValue: "3.0", values: null, numeric: true, description: "Reroute interval", use: null },
    ],
  },
  {
    id: "markers-and-fires",
    title: "Markers and fires",
    description: "Designated points, bullseye, auto-broadcast and coordinate entry.",
    keys: [
      { key: "spiUpdateDelay", group: "Designated points", type: "string", defaultValue: "5", values: null, numeric: true, description: "Designated point update period (seconds)", use: null },
      { key: "legacyFiresToolbarMode", group: "Designated points", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Old SPI toolbar", use: null },
      { key: "firesNumberOfSpis", group: "Designated points", type: "string", defaultValue: "1", values: [{ value: "1", label: "1" }, { value: "2", label: "2" }, { value: "3", label: "3" }], numeric: false, description: "Number of designated points", use: null },
      { key: "spiFahSize", group: "Designated points", type: "string", defaultValue: "30", values: null, numeric: true, description: "Final attack heading width", use: null },
      { key: "expandedDangerClose", group: "Designated points", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Wider danger-close search", use: null },
      { key: "bullseyeDistance", group: "Bullseye", type: "string", defaultValue: "2000", values: null, numeric: true, description: "Bullseye radius (m)", use: null },
      { key: "bullseyeNumRings", group: "Bullseye", type: "string", defaultValue: "4", values: null, numeric: true, description: "Bullseye ring count", use: null },
      { key: "bullseyeRadiusRings", group: "Bullseye", type: "string", defaultValue: "500", values: null, numeric: true, description: "Bullseye ring spacing (m)", use: null },
      { key: "bullseyeRingsVisible", group: "Bullseye", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Show bullseye rings", use: null },
      { key: "bullseyeDirection", group: "Bullseye", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Bullseye arrow direction", use: null },
      { key: "rapid_mgrs_dialog", group: "Coordinate entry", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Rapid MGRS entry", use: null },
      { key: "goto_tool_use_last_point", group: "Coordinate entry", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Go-to tool starts at the last point", use: null },
      { key: "hostileUpdateDelay", group: "Auto-broadcast", type: "string", defaultValue: "60", values: [{ value: "0", label: "Off" }, { value: "30", label: "30 seconds" }, { value: "60", label: "1 minute" }, { value: "90", label: "90 seconds" }, { value: "120", label: "2 minutes" }], numeric: false, description: "Auto-broadcast markers every (seconds, 0 off)", use: null },
      { key: "autosendStaleEnabled", group: "Auto-broadcast", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Stale timeout for auto-broadcast", use: null },
      { key: "autosendStaleInterval", group: "Auto-broadcast", type: "string", defaultValue: "30", values: null, numeric: true, description: "Auto-broadcast stale timeout", use: null },
      { key: "preference_broadcast_delete", group: "Auto-broadcast", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Allow others to delete auto-sent items", use: null },
      { key: "enableGeocoder", group: "Coordinate entry", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Address lookup (sends queries to an online geocoder)", use: "warning" },
    ],
  },
  {
    id: "notifications-and-chat",
    title: "Notifications and chat",
    description: "Alerts, chat notifications and the mesh chat.",
    keys: [
      { key: "alert_notification", group: "Alerts", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Show alert notifications", use: null },
      { key: "individual_alert_notification", group: "Alerts", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "One notification per alert", use: null },
      { key: "alert_audible", group: "Alerts", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Alert sound", use: null },
      { key: "alert_vibration", group: "Alerts", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Alert vibration", use: null },
      { key: "atakControlOtherUserNotification", group: "Notifications", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Notify about other users", use: null },
      { key: "fade_notification", group: "Notifications", type: "string", defaultValue: "90", values: [{ value: "30", label: "30 seconds" }, { value: "60", label: "1 minute" }, { value: "90", label: "90 seconds" }, { value: "120", label: "2 minutes" }, { value: "300", label: "5 minutes" }, { value: "600", label: "10 minutes" }, { value: "3600", label: "1 hour" }, { value: "-1", label: "Never" }], numeric: false, description: "Fade notifications after (seconds, -1 never)", use: null },
      { key: "enableToast", group: "Chat", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Show chat notifications", use: null },
      { key: "vibratePhone", group: "Chat", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Vibrate on chat", use: null },
      { key: "audibleNotify", group: "Chat", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Sound on chat", use: null },
      { key: "chatAddress", group: "Chat", type: "string", defaultValue: "224.10.10.1", values: null, numeric: false, description: "Mesh chat multicast address", use: "advanced" },
      { key: "chatPort", group: "Chat", type: "string", defaultValue: "17012", values: null, numeric: true, description: "Mesh chat port", use: "advanced" },
    ],
  },
  {
    id: "files-media-and-video",
    title: "Files, media and video",
    description: "File transfer, photos and video.",
    keys: [
      { key: "filesharingEnabled", group: "File sharing", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "File sharing", use: "form" },
      { key: "filesharingSizeThresholdNoGo", group: "File sharing", type: "string", defaultValue: "20", values: null, numeric: true, description: "Largest transfer (MB)", use: "form" },
      { key: "fileshareDownloadAttempts", group: "File sharing", type: "string", defaultValue: "10", values: null, numeric: true, description: "Download attempts", use: null },
      { key: "filesharingConnectionTimeoutSecs", group: "File sharing", type: "string", defaultValue: "10", values: null, numeric: true, description: "Transfer connection timeout (seconds)", use: null },
      { key: "filesharingTransferTimeoutSecs", group: "File sharing", type: "string", defaultValue: "10", values: null, numeric: true, description: "Transfer failure timeout (seconds)", use: null },
      { key: "filesharingAllServers", group: "File sharing", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Send packages through all servers", use: null },
      { key: "filesharingWebServerPort", group: "File sharing", type: "string", defaultValue: "8080", values: null, numeric: true, description: "Local HTTP file server port", use: "advanced" },
      { key: "filesharingSecureWebServerPort", group: "File sharing", type: "string", defaultValue: "8443", values: null, numeric: true, description: "Local HTTPS file server port", use: "advanced" },
      { key: "filesharingWebServerLegacyHttpEnabled", group: "File sharing", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Allow unencrypted HTTP transfers", use: "warning" },
      { key: "quickpic.camera_chooser", group: "Photos", type: "string", defaultValue: "System", values: [{ value: "System", label: "System" }, { value: "TakGeoCam", label: "TakGeoCam" }], numeric: false, description: "Camera app", use: null },
      { key: "prompt_photo_rename", group: "Photos", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Ask for a name when taking photos", use: null },
      { key: "secureDeleteTimeout", group: "Media and video", type: "string", defaultValue: "10", values: null, numeric: true, description: "Secure delete timeout", use: null },
      { key: "prefs_use_klv_elevation", group: "Media and video", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Prefer KLV frame centre elevation", use: null },
      { key: "video_disable_audio", group: "Media and video", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Video without audio", use: null },
      { key: "video_mute_when_hidden", group: "Media and video", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Mute hidden video", use: null },
    ],
  },
  {
    id: "connection-and-mesh",
    title: "Connection and mesh",
    description: "Server connection behaviour, mesh mode, elevation data and peripherals.",
    keys: [
      { key: "displayServerConnectionWidget", group: "Server", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Show the server connection widget", use: "form" },
      { key: "monitorServerConnections", group: "Server", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Monitor server connections", use: null },
      { key: "enableNonStreamingConnections", group: "Mesh", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Mesh network mode (multicast SA)", use: "form" },
      { key: "autoDisableMeshSAWhenStreaming", group: "Mesh", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Turn mesh SA off while connected to a server", use: null },
      { key: "tcpConnectTimeout", group: "Network", type: "string", defaultValue: "20", values: null, numeric: true, description: "TCP connect timeout (seconds)", use: null },
      { key: "udpNoDataTimeout", group: "Network", type: "string", defaultValue: "30", values: null, numeric: true, description: "Multicast rejoin interval (seconds)", use: "advanced" },
      { key: "multicastTTL", group: "Network", type: "string", defaultValue: "64", values: null, numeric: true, description: "Multicast TTL", use: "advanced" },
      { key: "network_multicast_loopback", group: "Network", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Multicast loopback", use: "advanced" },
      { key: "network_quic_enabled", group: "Network", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "QUIC protocol", use: "advanced" },
      { key: "onlyStreamingWithVPN", group: "Server", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Connect to the server only over VPN", use: "warning" },
      { key: "ppp0_highspeed_capable", group: "Network", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Point-to-point link is fast", use: "advanced" },
      { key: "waveRelayRedirect", group: "Network", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Legacy Wave Relay redirect", use: "advanced" },
      { key: "insertDestInDirectedCoT", group: "Network", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Add destinations to directed CoT for gateways", use: "advanced" },
      { key: "apiCertEnrollmentKeyLength", group: "Server", type: "string", defaultValue: "4096", values: null, numeric: true, description: "Key length for enrollment (bits)", use: "advanced" },
      { key: "atakControlBluetooth", group: "Connected devices", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Bluetooth devices", use: null },
      { key: "atakBluetoothReconnectSeconds", group: "Connected devices", type: "string", defaultValue: "180", values: null, numeric: true, description: "Bluetooth reconnect time (seconds)", use: null },
      { key: "nonBluetoothLaserRangeFinder", group: "Connected devices", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Laser range finders without Bluetooth", use: null },
      { key: "prefs_dted_stream", group: "Elevation and map data", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Stream elevation data", use: "warning" },
      { key: "prefs_dted_stream_server", group: "Elevation and map data", type: "string", defaultValue: "tak.gov", values: null, numeric: false, description: "Elevation server", use: "warning" },
      { key: "force_dted_elevation_only", group: "Elevation and map data", type: "boolean", defaultValue: null, values: null, numeric: false, description: "Only DTED elevation", use: null },
      { key: "prefs_enable_smart_cache", group: "Elevation and map data", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Cache map tiles while browsing", use: null },
      { key: "prefs_smart_cache_download_limit", group: "Elevation and map data", type: "string", defaultValue: "5000000", values: null, numeric: true, description: "Smart cache limit (bytes)", use: null },
      { key: "eud_api_sync_mapsources", group: "Plugins and tak.gov", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "tak.gov device link: sync map sources", use: null },
      { key: "eud_api_sync_plugins", group: "Plugins and tak.gov", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "tak.gov device link: sync plugin list", use: null },
      { key: "eud_api_disable_option", group: "Plugins and tak.gov", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Turn off the tak.gov device link", use: null },
      { key: "atakPluginScanningOnStartup", group: "Plugins and tak.gov", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Load plugins on start", use: null },
      { key: "repoStartupSync", group: "Plugins and tak.gov", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Sync the plugin repository on start", use: null },
    ],
  },
  {
    id: "contact-details",
    title: "Contact details",
    description: "Personal values; only for single members.",
    keys: [
      { key: "userRemarks", group: "Marker", type: "string", defaultValue: null, values: null, numeric: false, description: "Remarks shown with the own marker", use: "member" },
      { key: "saHasPhoneNumber", group: "Contact", type: "boolean", defaultValue: "true", values: null, numeric: false, description: "Publish the phone number", use: "member" },
      { key: "saAlternativeNumber", group: "Contact", type: "string", defaultValue: null, values: null, numeric: false, description: "Alternative phone number", use: "member" },
      { key: "preferAltNumber", group: "Contact", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Prefer the alternative number", use: "member" },
      { key: "saSipAddressAssignment", group: "Contact", type: "string", defaultValue: "No VoIP", values: [{ value: "No VoIP", label: "No VoIP" }, { value: "Manual Entry", label: "Manual entry" }, { value: "Use IP Address", label: "IP address" }, { value: "Use Callsign and IP Address", label: "Callsign and IP address" }], numeric: false, description: "How the VoIP address is set (stored as the English option text)", use: "member" },
      { key: "saSipAddress", group: "Contact", type: "string", defaultValue: null, values: null, numeric: false, description: "VoIP address", use: "member" },
      { key: "saXmppUsername", group: "Contact", type: "string", defaultValue: null, values: null, numeric: false, description: "XMPP user name", use: "member" },
      { key: "saEmailAddress", group: "Contact", type: "string", defaultValue: null, values: null, numeric: false, description: "Email address", use: "member" },
      { key: "saURN", group: "Contact", type: "string", defaultValue: null, values: null, numeric: true, description: "Unit reference number", use: "member" },
    ],
  },
  {
    id: "diagnostics",
    title: "Diagnostics",
    description: "Logging and metrics for troubleshooting.",
    keys: [
      { key: "loggingfile", group: "Logging", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Write logcat to a file", use: "advanced" },
      { key: "loggingfile_error_only", group: "Logging", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Only errors in the log file", use: "advanced" },
      { key: "loggingfile_upload_debug", group: "Logging", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Upload debug logs", use: "advanced" },
      { key: "enableAutoUploadLogs", group: "Logging", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Upload app logs automatically", use: "advanced" },
      { key: "lognettraffictofile", group: "Logging", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Log network traffic", use: "warning" },
      { key: "collect_metrics", group: "Metrics", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Collect metrics", use: "advanced" },
      { key: "realtime_metrics", group: "Metrics", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Live metrics", use: "advanced" },
      { key: "generate_full_pool", group: "Metrics", type: "boolean", defaultValue: null, values: null, numeric: false, description: "Advanced CoT recorder", use: "advanced" },
      { key: "generate_detail_pool", group: "Metrics", type: "boolean", defaultValue: null, values: null, numeric: false, description: "Advanced CoT detail recorder", use: "advanced" },
      { key: "atakDeveloperTools", group: "Developer", type: "boolean", defaultValue: null, values: null, numeric: false, description: "Developer tools", use: "advanced" },
      { key: "override_permission_request", group: "Developer", type: "boolean", defaultValue: "false", values: null, numeric: false, description: "Skip the permission request", use: "warning" },
    ],
  },
];

/** Keys OpenMeshTak never sends from event settings, with the reason shown to administrators. */
export const BLOCKED_ATAK_PREFERENCES: Array<{ key: string; reason: string }> = [
  { key: "locationCallsign", reason: "OpenMeshTak sets the member's callsign" },
  { key: "locationTeam", reason: "OpenMeshTak sets the event group's team color" },
  { key: "atakRoleType", reason: "OpenMeshTak sets the member's TAK role" },
  { key: "locationUseWRCallsign", reason: "Would replace the callsign" },
  { key: "bestDeviceUID", reason: "Device identity" },
  { key: "caPassword", reason: "Secret" },
  { key: "clientPassword", reason: "Secret" },
  { key: "updateServerCaPassword", reason: "Secret" },
  { key: "apiSecureServerPort", reason: "Core sets it from the TAK server settings" },
  { key: "apiUnsecureServerPort", reason: "Core offers no unsecured API" },
  { key: "apiCertEnrollmentPort", reason: "Core sets it from the TAK server settings" },
  { key: "deviceProfileEnableOnConnect", reason: "Core controls profile delivery" },
  { key: "certEnrollmentExport", reason: "Would allow exporting the client certificate and key" },
  { key: "pref_import_pref_action", reason: "DENY would block every later OpenMeshTak profile" },
  { key: "atakUpdateServerUrl", reason: "Points devices at an APK source; not an event decision" },
  { key: "appMgmtEnableUpdateServer", reason: "Belongs with the update server URL" },
  { key: "httpClientPermissiveMode", reason: "Weakens TLS checks" },
  { key: "network_config", reason: "Device network setup (ISRV hardware)" },
  { key: "network_dhcp", reason: "Device network setup (ISRV hardware)" },
  { key: "network_static_ip_address", reason: "Device network setup (ISRV hardware)" },
  { key: "network_static_subnet_mask", reason: "Device network setup (ISRV hardware)" },
  { key: "network_static_gateway", reason: "Device network setup (ISRV hardware)" },
  { key: "network_static_dns1", reason: "Device network setup (ISRV hardware)" },
  { key: "network_static_dns2", reason: "Device network setup (ISRV hardware)" },
  { key: "coordinate_entry_tabs", reason: "String set; the .pref format has no set class" },
  { key: "default_gps_icon", reason: "One of three radio buttons ATAK switches together" },
  { key: "team_color_gps_icon", reason: "One of three radio buttons ATAK switches together" },
  { key: "custom_color_gps_icon_pref", reason: "One of three radio buttons ATAK switches together" },
  { key: "savePrefs", reason: "Action, not a stored value" },
  { key: "loadPrefs", reason: "Action, not a stored value" },
];
